// APP
export const SET_LANGUAGE = "SET_LANGUAGE";
// HEADER
export const GET_USERDETAILS = "GET_USERDETAILS";
export const GET_USERDETAILS_SUCCESS = "GET_USERDETAILS_SUCCESS";
export const GET_USERDETAILS_FAILURE = "GET_USERDETAILS_FAILURE";
export const SET_FEEDBACK = "SET_FEEDBACK";
// FOOTER
export const TOGGLE_CHECKBOX_ELEMENT = "TOGGLE_CHECKBOX_ELEMENT";
// USER_MANAGMENT
export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";
export const CHANGE_USERS_DISPLAY = "CHANGE_USERS_DISPLAY";
